version: "3"

services:
  redis:
    image: redis
    networks:
      - back-end

  db:
    image: postgress:9.4
    networks:
      - back-end

  vote:
    build: ./vote
    ports:
      - 5000:80
    links: 
      - redis
    depends_on:
      - vote
    networks:
      - front-end
      - back-end

  result:
    image: result-app
    ports:
      - 5001:80
    links:
      - db
    networks:
      - front-end
      - back-end

  worker:
    build: ./worker
    links:
      - redis
      - db
    networks:
      - back-end

networks:
  front-end:
  back-end: